/* ============================================================
   purchases.ts — subscriptions, via RevenueCat + StoreKit 2.

   Three modes, decided at runtime by `purchaseMode()`:

     'store'        native build with an API key — the real thing
     'mock'         web / dev — fake receipts so preview and e2e work
     'unavailable'  native build with NO api key — the gate stays
                    shut and no prices are shown. Deliberately not a
                    free pass: shipping a build that hands the app
                    out for nothing, or that shows invented prices,
                    is worse than one that says it is unavailable.

   ⚠️ Under StoreKit 2 (purchases-ios 5.x, which this wraps),
   transactions are silently never recorded unless the In-App
   Purchase Key in the RevenueCat dashboard was generated by THIS
   app's Apple account. The symptom is $0 in RevenueCat while Apple
   really is charging people, and paying users locked out. See
   notes/REVENUECAT-SETUP.md step 3.
   ============================================================ */

import { Capacitor } from '@capacitor/core'
import {
  Purchases,
  LOG_LEVEL,
  type PurchasesPackage,
  type CustomerInfo,
} from '@revenuecat/purchases-capacitor'

/** Must match the entitlement identifier in the RevenueCat dashboard
    exactly. A mismatch here unlocks nothing for anyone who pays. */
export const ENTITLEMENT_ID = 'premium'

const API_KEY = (import.meta.env.VITE_REVENUECAT_IOS_KEY as string | undefined)?.trim() || ''

export type PlanId = 'weekly' | 'monthly' | 'yearly'

export type Plan = {
  id: PlanId
  productId: string
  title: string
  /** localized, e.g. "$7.99" or "￥1,200" — from the store when live */
  price: string
  per: string
  equivalent: string
  badge?: string
  periodDays: number
}

/** RevenueCat's standard package identifiers, in the offering. */
const PACKAGE_FOR: Record<PlanId, string> = {
  weekly: '$rc_weekly',
  monthly: '$rc_monthly',
  yearly: '$rc_annual',
}

/* Shape and copy for the three tiers. Prices here are the US
   defaults and act as the fallback; the live paywall overwrites
   them with the store's localized strings. */
export const PLANS: Plan[] = [
  {
    id: 'weekly',
    productId: 'jojot.premium.weekly',
    title: 'Weekly',
    price: '$7.99',
    per: '$7.99 per week',
    equivalent: '$1.14 / day',
    periodDays: 7,
  },
  {
    id: 'monthly',
    productId: 'jojot.premium.monthly',
    title: 'Monthly',
    price: '$14.99',
    per: '$14.99 per month',
    equivalent: '$3.75 / week',
    badge: 'Most popular',
    periodDays: 30,
  },
  {
    id: 'yearly',
    productId: 'jojot.premium.yearly',
    title: 'Yearly',
    price: '$49.99',
    per: '$49.99 per year',
    equivalent: '$4.16 / month',
    badge: 'Save 72%',
    periodDays: 365,
  },
]

export const DEFAULT_PLAN: PlanId = 'monthly'

export function getPlan(id: PlanId): Plan {
  return PLANS.find((p) => p.id === id) ?? PLANS[1]
}

export type Entitlement = {
  planId: PlanId
  productId: string
  purchasedISO: string
  renewsISO: string
}

export type PurchaseResult =
  | { ok: true; entitlement: Entitlement }
  | { ok: false; reason: 'cancelled' | 'failed' | 'none-to-restore' }

export type PurchaseMode = 'store' | 'mock' | 'unavailable'

export function purchaseMode(): PurchaseMode {
  if (!Capacitor.isNativePlatform()) return 'mock'
  return API_KEY ? 'store' : 'unavailable'
}

/* ------------------------------------------------------------------ */
/* Mock — web preview and the e2e suite                                */
/* ------------------------------------------------------------------ */

const RECEIPT_KEY = 'jojot:receipt:v1'
const LATENCY = 850

function addDays(iso: string, days: number): string {
  const d = new Date(iso)
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

function mockEntitlement(plan: Plan): Entitlement {
  const today = new Date().toISOString().slice(0, 10)
  return {
    planId: plan.id,
    productId: plan.productId,
    purchasedISO: today,
    renewsISO: addDays(today, plan.periodDays),
  }
}

function readReceipt(): Entitlement | null {
  try {
    const raw = localStorage.getItem(RECEIPT_KEY)
    return raw ? (JSON.parse(raw) as Entitlement) : null
  } catch {
    return null
  }
}

export function clearReceipt() {
  try {
    localStorage.removeItem(RECEIPT_KEY)
  } catch {
    /* ignore */
  }
}

/* ------------------------------------------------------------------ */
/* RevenueCat                                                          */
/* ------------------------------------------------------------------ */

let configured = false
let cachedPackages: PurchasesPackage[] = []

/** Safe to call more than once; only the first call configures. */
export async function initPurchases(): Promise<void> {
  if (purchaseMode() !== 'store' || configured) return
  try {
    await Purchases.setLogLevel({ level: import.meta.env.DEV ? LOG_LEVEL.DEBUG : LOG_LEVEL.ERROR })
    await Purchases.configure({ apiKey: API_KEY })
    configured = true
  } catch {
    // leave `configured` false — the app will show the paywall as
    // unavailable rather than pretending anything succeeded
  }
}

/** Derive the "$4.16 / month"-style line from the real price. */
function equivalentLine(amount: number, currency: string, id: PlanId): string {
  const fmt = (n: number) => {
    try {
      return new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(n)
    } catch {
      return n.toFixed(2)
    }
  }
  if (id === 'weekly') return `${fmt(amount / 7)} / day`
  if (id === 'monthly') return `${fmt(amount / 4.345)} / week`
  return `${fmt(amount / 12)} / month`
}

/**
 * The tiers to show on the paywall, with the store's own localized
 * prices when they are available. Falls back to the static US copy
 * in 'mock', and returns [] in 'unavailable' so the paywall can say
 * so instead of inventing numbers.
 */
export async function loadPlans(): Promise<Plan[]> {
  const mode = purchaseMode()
  if (mode === 'mock') return PLANS
  if (mode === 'unavailable') return []

  await initPurchases()
  if (!configured) return []

  try {
    const { current } = await Purchases.getOfferings()
    if (!current?.availablePackages?.length) return []
    cachedPackages = current.availablePackages

    const priced = PLANS.map((base) => {
      const pkg = cachedPackages.find((p) => p.identifier === PACKAGE_FOR[base.id])
      if (!pkg) return null
      const { priceString, price, currencyCode, identifier } = pkg.product
      return {
        ...base,
        productId: identifier,
        price: priceString,
        per: `${priceString} per ${base.id === 'yearly' ? 'year' : base.id.replace('ly', '')}`,
        equivalent: equivalentLine(price, currencyCode, base.id),
      }
    }).filter((p): p is Plan => p !== null)

    return priced
  } catch {
    return []
  }
}

function entitlementFrom(info: CustomerInfo): Entitlement | null {
  const active = info.entitlements.active[ENTITLEMENT_ID]
  if (!active) return null

  const productId = active.productIdentifier
  const matched = PLANS.find((p) => productId.includes(p.id)) ?? getPlan(DEFAULT_PLAN)

  return {
    planId: matched.id,
    productId,
    purchasedISO: (active.latestPurchaseDate ?? '').slice(0, 10),
    renewsISO: (active.expirationDate ?? '').slice(0, 10),
  }
}

/**
 * The result of asking the store who this user is.
 *
 * 'unknown' is not the same as no entitlement, and conflating the two
 * is how you lock paying customers out: a flat `null` on a network
 * blip would overwrite the cached entitlement and drop a subscriber
 * onto the paywall. Callers must leave their cache alone on 'unknown'.
 */
export type EntitlementCheck =
  | { status: 'ok'; entitlement: Entitlement | null }
  | { status: 'unknown' }

/**
 * Ask the store who this user is. When it answers, it is the
 * authority — a lapsed or refunded subscription closes the gate, and
 * a reinstall opens it without the user hunting for Restore.
 */
export async function checkEntitlement(): Promise<EntitlementCheck> {
  const mode = purchaseMode()
  if (mode === 'mock') return { status: 'ok', entitlement: readReceipt() }
  // no key: nothing can be verified, so don't touch what is cached
  if (mode === 'unavailable') return { status: 'unknown' }

  await initPurchases()
  if (!configured) return { status: 'unknown' }

  try {
    const { customerInfo } = await Purchases.getCustomerInfo()
    return { status: 'ok', entitlement: entitlementFrom(customerInfo) }
  } catch {
    return { status: 'unknown' }
  }
}

export async function buy(planId: PlanId): Promise<PurchaseResult> {
  const mode = purchaseMode()

  if (mode === 'mock') {
    const plan = getPlan(planId)
    await new Promise((r) => setTimeout(r, LATENCY))
    const entitlement = mockEntitlement(plan)
    try {
      localStorage.setItem(RECEIPT_KEY, JSON.stringify(entitlement))
    } catch {
      /* ignore */
    }
    return { ok: true, entitlement }
  }

  if (mode === 'unavailable') return { ok: false, reason: 'failed' }

  await initPurchases()
  if (!configured) return { ok: false, reason: 'failed' }

  if (!cachedPackages.length) await loadPlans()
  const pkg = cachedPackages.find((p) => p.identifier === PACKAGE_FOR[planId])
  if (!pkg) return { ok: false, reason: 'failed' }

  try {
    const { customerInfo } = await Purchases.purchasePackage({ aPackage: pkg })
    const entitlement = entitlementFrom(customerInfo)
    if (!entitlement) return { ok: false, reason: 'failed' }
    return { ok: true, entitlement }
  } catch (e) {
    // RevenueCat surfaces a cancellation as a thrown error with a flag
    const cancelled = (e as { userCancelled?: boolean; code?: string })?.userCancelled
    return { ok: false, reason: cancelled ? 'cancelled' : 'failed' }
  }
}

export async function restore(): Promise<PurchaseResult> {
  const mode = purchaseMode()

  if (mode === 'mock') {
    await new Promise((r) => setTimeout(r, LATENCY))
    const found = readReceipt()
    return found ? { ok: true, entitlement: found } : { ok: false, reason: 'none-to-restore' }
  }

  if (mode === 'unavailable') return { ok: false, reason: 'failed' }

  await initPurchases()
  if (!configured) return { ok: false, reason: 'failed' }

  try {
    const { customerInfo } = await Purchases.restorePurchases()
    const entitlement = entitlementFrom(customerInfo)
    return entitlement
      ? { ok: true, entitlement }
      : { ok: false, reason: 'none-to-restore' }
  } catch {
    return { ok: false, reason: 'failed' }
  }
}

/* ------------------------------------------------------------------ */

/* Apple's standard EULA is fine to link as the Terms of Use, and saves
   hosting a custom one. The privacy policy must be ours, though —
   this used to point at apple.com/legal/privacy, which is Apple's own
   policy and says nothing about this app.

   ⚠️ Both links must open. A paywall that renders these as plain text
   with no handler is a Guideline 3.1.2 rejection, and the privacy URL
   must return 200 to a logged-out fetch, not just in your browser. */
/** Apple's own subscription management screen — the only place a
    subscription can genuinely be cancelled. */
export const MANAGE_SUBSCRIPTION_URL = 'https://apps.apple.com/account/subscriptions'

export const TERMS_URL = 'https://www.apple.com/legal/internet-services/itunes/dev/stdeula/'
export const PRIVACY_URL = 'https://jojot.vercel.app/privacy/'
export const SUPPORT_URL = 'https://jojot.vercel.app/'
